USE [master]
GO

/****** Object:  Database [b]    Script Date: 10/21/2019 7:24:06 PM ******/
CREATE DATABASE [b]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'b', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\b.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'b_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\b_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [b] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [b].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [b] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [b] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [b] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [b] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [b] SET ARITHABORT OFF 
GO

ALTER DATABASE [b] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [b] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [b] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [b] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [b] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [b] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [b] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [b] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [b] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [b] SET  ENABLE_BROKER 
GO

ALTER DATABASE [b] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [b] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [b] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [b] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [b] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [b] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [b] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [b] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [b] SET  MULTI_USER 
GO

ALTER DATABASE [b] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [b] SET DB_CHAINING OFF 
GO

ALTER DATABASE [b] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [b] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [b] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [b] SET QUERY_STORE = OFF
GO

ALTER DATABASE [b] SET  READ_WRITE 
GO

